/* Generated by MyraPad at 11/22/2023 10:16:06 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace BrickShooter.UI
{
	partial class LossScreen: Grid
	{
		private void BuildUI()
		{
			var panel1 = new Panel();
			panel1.Background = new SolidBrush("#000000C8");
			Grid.SetRowSpan(panel1, 3);

			var label1 = new Label();
			label1.Text = "YOU DIED";
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			var textBox1 = new TextBox();
			textBox1.Text = "Try again";
			textBox1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			textBox1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			textBox1.Background = new SolidBrush("#00000000");

			_retryButton = new Button();
			_retryButton.Width = 250;
			_retryButton.Height = 100;
			_retryButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_retryButton.Id = "_retryButton";
			Grid.SetRow(_retryButton, 1);
			_retryButton.Content = textBox1;

			var textBox2 = new TextBox();
			textBox2.Text = "Give up";
			textBox2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			textBox2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			textBox2.Background = new SolidBrush("#00000000");

			_quitButton = new Button();
			_quitButton.Width = 250;
			_quitButton.Height = 100;
			_quitButton.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_quitButton.Id = "_quitButton";
			Grid.SetRow(_quitButton, 2);
			_quitButton.Content = textBox2;

			
			ColumnSpacing = 1;
			RowSpacing = 3;
			Widgets.Add(panel1);
			Widgets.Add(label1);
			Widgets.Add(_retryButton);
			Widgets.Add(_quitButton);
		}

		
		public Button _retryButton;
		public Button _quitButton;
	}
}
